spring:
  datasource:
    url: jdbc:mysql://localhost:3306/write-now?charset=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: dustn@@0317
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # database-platform: kr.co.apexsoft.gradnet2.entity._config.MysqlCustomDialect
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

---
spring:
  config:
    activate:
      on-profile: product
  datasource:
    url: ${PRODUCT_DATABASE_URL}
    username: ${PRODUCT_DATABASE_USERNAME}
    password: ${PRODUCT_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties.hibernate:
      show_sql: false
