server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      min-spare: 30


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/write-now?charset=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: dustn@@0317
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 3000
      minimum-idle: 100

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: ERROR

jwt:
  issuer: test@test.com
  secret_key: aziBwQMoAxTLMmLkvIslUfQdTnrRyOBAvBxyOxQjhtcSSpUeyBkVOHKCgsPS

frontDomain: http://localhost:3000

naver:
  cloud:
    accessKey: ${NAVER_ACCESS_KEY}
    secretKey: ${NAVER_SECRET_KEY}
    bucketName: ${NAVER_BUCKET_NAME}

file:
  rootDir: /opt
  baseDir: /write-now

management:
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      base-path: /monitor
      exposure:
        include:
          - prometheus
          - health
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  server:
    port: 8085

