spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/write-now
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  security:
    user:
      name: admin
      password: 1234
