spring:
  profiles:
    include:
      - database
logging:
  level:
    root: ERROR
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: ERROR

jwt:
  issuer: test@test.com
  secret_key: MFswDQYJKoZIhvcNAQEBBQADSgAwRwJAcFvaLSkWsphMsoBYkSGImf

frontDomain: http://localhost:3000
---
spring:
  config:
    activate:
      on-profile: product
logging:
  level:
    root: error
    org.springframework.security: DEBUG
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: ERROR
jwt:
  issuer: { JWT_ISSUER }
  secret_key: { JWT_SECRET_KEY }
