name: Java CI/CD with Gradle

on:
  push:
    branches: [ "master" ]
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: clean build -x test
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: write-now-jar
        path: build/libs/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: write-now-jar
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.WRITE_NOW_SSH_SECRET }}
      - name: Add remote server to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -T 240 -p 6666 ${{ secrets.WRITE_NOW_SERVER_IP }} >> ~/.ssh/known_hosts
      - name: SCP transfer
        run: scp -P 6666 *.jar root@${{ secrets.WRITE_NOW_SERVER_IP }}:/deploy
      - name: Create .env file And Transfer
        run: |
          echo "PRODUCT_DATABASE_URL=$WRITE_NOW_DATABASE_URL" >> .env
          echo "PRODUCT_DATABASE_USERNAME=$WRITE_NOW_DATABASE_USERNAME" >> .env
          echo "PRODUCT_DATABASE_PASSWORD=$WRITE_NOW_DATABASE_PASSWORD" >> .env
          echo "JWT_ISSUER=$WRITE_NOW_JWT_ISSUER" >> .env
          echo "JWT_SECRET_KEY=$WRITE_NOW_JWT_SECRET" >> .env
          scp -P 6666 .env root@${{ secrets.WRITE_NOW_SERVER_IP }}:/
        env:
          WRITE_NOW_DATABASE_URL: ${{ secrets.WRITE_NOW_DATABASE_URL }}
          WRITE_NOW_DATABASE_USERNAME: ${{ secrets.WRITE_NOW_DATABASE_USERNAME }}
          WRITE_NOW_DATABASE_PASSWORD: ${{ secrets.WRITE_NOW_DATABASE_PASSWORD }}
          WRITE_NOW_JWT_ISSUER: ${{ secrets.WRITE_NOW_JWT_ISSUER }}
          WRITE_NOW_JWT_SECRET: ${{ secrets.WRITE_NOW_JWT_SECRET }}
      - name: Execute remote commands
        run: |
          ssh -p 6666 root@${{ secrets.WRITE_NOW_SERVER_IP }} "sudo sh /deploy/test.sh"
